name = "backend"
compatibility_date = "2024-07-15"


 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODg1YjY0Y2UtMzcyMS00N2Y1LTk2ZmEtODNlMGQ3MmVjNzYzIiwidGVuYW50X2lkIjoiYmMyODVmMjdkODJhNTUzZDE4MjllNzQxMzc1ODU1NGU5NjJkMWUyNTFkOTQ4MjExZWMxZTJkNDE5ZTllNGNhOSIsImludGVybmFsX3NlY3JldCI6ImVlYjQzNzA1LWU3OGUtNDQ3Ni04OGExLTVlOTM2NGZhN2U1ZCJ9.k8a6Ed_salsTZbU6KUsmIiDpzjffwAByOPfvyholR1s"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"